# Github workflow syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: go mod download -x

      - name: Run tests
        run: go test -v -p 1 -count=1 -race -cover ./...
